
QIIME2_ENV: "source activate /home/jeffbrady/miniconda3/envs/qiime2-2020.6"

# Download pre-trained silva database for qiime2

# Get the pre-trained full-length SILVA 99% classifier
SILVA_CLASSIFIER: "https://data.qiime2.org/2020.6/common/silva-138-99-nb-classifier.qza"

# Get the raw preformatted sequences
SILVA_SEQUENCES: "https://data.qiime2.org/2020.6/common/silva-138-99-seqs.qza"

# Get the preformatted taxonomy
SILVA_TAXONOMY: "https://data.qiime2.org/2020.6/common/silva-138-99-tax.qza"


# Unite fungi databse for qiime2
UNITE_URL: "https://files.plutof.ut.ee/public/orig/1D/31/1D31FA3A308BDC2FB2750D62C0AA40C5058C15405A3CC5C626CC3A3F5E3903ED.tgz"

# Set tool specific parameters
# Sample primers for 341F and 806R
parameters:
    extract_sequence: 
        forward_primer: "GTGCCAGCMGCCGCGGTAA"
        reverse_primer: "GGACTACHVGGGTWTCTAAT"
        min_length: 100
        max_length: 800
        trunc_length: 585
