sample_file: "config/sample.tsv"
metadata: "00.mapping/outdoors.tsv"
samples: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2']
project_dir: "~/hinuman_analysis/16S_illumina/"
# what type of amplicon are we analyzing
# options are
# "16S", "18S" and "ITS"
amplicon: "16S" 
# A coloumn in metada for grouping bar plot and for statistics
group: "Treatment"
# Three possible mode
# pair - paired-end reads without joining
# single - single end reads, joining of unnecessary
# merge - merge paired end reads
# if you will select to join the reads 
# # make sure to modify the -m -t flags of pear in the run_pear.pl script 
# before running the workflow

mode: "pair" # "single" or "merge"

# What method should be used in merging reads
# options are "pear" or "vsearch"
# for merging with pear or vsearch, repectively
merge_method: "pear"

# ASV or zoTUs denoising and clustering method. Can be "dada2" or "deblur"
denoise_method: "dada2"


# path to your manifest file - see the example folder for examples
MANIFEST: "sequence_data/pe-MANIFEST"
project_name: "mankai"

QIIME2_ENV: "source activate qiime2-2020.6"
PERL5LIB: "export PERL5LIB='/gpfs0/bioinfo/users/obayomi/miniconda3/envs/qiime2-2020.6/lib/site_perl/5.26.2/x86_64-linux-thread-multi'"

# # Add this line to everdy script to avoid device out of space error
TEMP_DIR: "export TEMPDIR=~/hinuman_analysis/18S_illumina/tmp/ TMPDIR=~/hinuman_analysis/18S_illumina/tmp/"

# set the path to the appropriate classifier for assigning taxonomy
# Here i chose the classifier for silva for bacteria (16S) and protist (18S) analysis
# For Fungi set to the path of a pre trained unite database classifier
classifier: "/gpfs0/bioinfo/users/obayomi/databases/q2_database/silva-138-99-nb-classifier.qza"

# To figure out the total number of sequences ("Total freqency") 
# to be used to determine the minuminum frequency for filtering out
# rare taxa, examine "08.Filter_feature_table/taxa_filtered_table.qzv".
# To calculate, multiply the total number of sequences by 0.00005 (0.005%)
# Assign reult of your calulation below as the minimum frequency 
# for filtering out rare taxa
minimum_frequency: 3

# Change this and re-run core diversity step if need. Determine this number by
# examiming "08.Filter_feature_table/filtered_table.qzv". Either choose the
# minimum sequence count or choose the minimum sequence count 
# that will be enough to capture the diversity of your samples and still
# not lose a lot of samples
rarefaction_depth: 1000


# Full paths to the specified programs
programs_path:
    multiqc: "/gpfs0/bioinfo/apps/Miniconda2/Miniconda_v4.3.21/envs/Metagenomics/bin/multiqc"
    fastqc: "/gpfs0/bioinfo/apps/Miniconda2/Miniconda_v4.3.21/envs/Metagenomics/bin/fastqc"
    parallel: "/gpfs0/bioinfo/users/obayomi/bin/parallel"
    run_pear: "/gpfs0/bioinfo/users/obayomi/microbiome_helper/run_pear.pl"


# Set tool specific parameters
parameters:
    extract_sequence: 
        forward_primer: "GTGCCAGCMGCCGCGGTAA"
        reverse_primer: "GGACTACHVGGGTWTCTAAT"
        min_length: 100
        max_length: 800
        trunc_length: 585
    vsearch:
        join_pairs:
            truncqual: 20
            minimum_length: 400
            maximum_Ns: 20
            minimum_merge_length: 400
            minimum_merge_length: 600

    dada2:
        mode: "paired" # single
        trunc_length_forward: 400
        trunc_length_reverse: 400
        trim_length_forward: 0
        trim_length_reverse: 0
        threads: 30

    # --p-trim-length n which truncates the sequences at position n
    # In general, the Deblur developers recommend setting this value
    # to a length where the median quality score begins to drop too low 
    deblur:
        trunc_length: 40
    # Parameters to argument of qiime feature-table group
    # when grouping the feature table for making grouped taxa barplots
    group_taxa_plot:
        category: "treatment" # --m-metadata-column argument
        mode: "sum" # --p-mode argument

    
    beta_diversity_significance:
         categories: ["treatment", "B12_supplemetation"] # a
